FROM hypriot/rpi-mysql:5.5
MAINTAINER Brother In Arms <project.biarms@gmail.com>

# (Upgrade to 1.9 was inspired by https://github.com/rothgar/rpi-wordpress/blob/master/mysql/Dockerfile)
# add gosu for easy step-down from root
ENV GOSU_VERSION 1.9
RUN set -x \
	&& apt-get update && apt-get install -y --no-install-recommends ca-certificates wget && rm -rf /var/lib/apt/lists/* \
	&& wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture | awk -F- '{ print $NF }')" \
	&& wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture | awk -F- '{ print $NF }').asc" \
	&& export GNUPGHOME="$(mktemp -d)" \
	&& gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
	&& gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
	&& rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc \
	&& chmod +x /usr/local/bin/gosu \
	&& gosu nobody true \
	&& apt-get purge -y --auto-remove ca-certificates wget \
        && rm -rf /var/lib/apt/lists/*

VOLUME /var/lib/mysql

# ENV MYSQL_MAJOR 5.5
# ADD https://raw.githubusercontent.com/docker-library/mysql/master/${MYSQL_MAJOR}/docker-entrypoint.sh /usr/local/bin/
COPY entrypoint-5.5.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh \
 && chown mysql:mysql /usr/local/bin/docker-entrypoint.sh \
 && rm /entrypoint.sh \
 && ln -s usr/local/bin/docker-entrypoint.sh /entrypoint.sh # backwards compat
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

EXPOSE 3306
CMD ["mysqld"]

# (inspired by https://github.com/rothgar/rpi-wordpress/blob/master/mysql/Dockerfile)
ADD my-small.cnf /etc/mysql/conf.d/